### PR TITLE
Docker Registry v2

### PR DESCRIPTION
**Pull request by cmheisel**
Switches to the registry:2 image/tag, updates the tests to match

### CODE REVIEW

**Comment by tehranian** [comment]
@cmheisel Awesome, thanks for doing this!

One question: It looks like the on-disk data format for the registry has changed from v1 to v2: https://github.com/docker/migrator. Any thoughts on how we could facilitate this change for folks who have already used this role to stand up the v1 registry?

One potential solution: Don't address the issue directly. Instead, use semantic versioning on the role to indicate a breaking change. What do you think?

**Comment by tehranian** [comment]
One nit: The links in the README for the registry need to be changed from https://github.com/docker/docker-registry to https://github.com/docker/distribution

**Comment by cmheisel** [comment]
@tehranian Cool, I'll make some updates and resubmit

**Comment by cmheisel** [comment]
Ignore this #8 is newer

**Pull request closed without merging**
